### PR TITLE
Add support for parsing SHELL instruction

### PR DESCRIPTION
**Pull request by backus**
Let me know if I missed something. This is basically the first haskell I've written

### CODE REVIEW

**Comment by backus** [comment]
I also checked to confirm that some of the dockerfiles in the repos the integration tests pull down do indeed include `SHELL` instruction usage. For example: https://github.com/docker-library/mongo/blob/master/3.0/windows/windowsservercore/Dockerfile#L3

**Comment by backus** [comment]
@lukasmartinelli I think this is ready for review

**Comment by lukasmartinelli** [comment]
> Let me know if I missed something. This is basically the first haskell I've written

Awesome! Pretty good for the first Haskell program! Looks elegant.

**Comment by backus** [comment]
@lukasmartinelli :smile:

**Pull request merged**
