### PR TITLE
Better CLI interface

### PR DESCRIPTION
**Pull request by lukasmartinelli**
- Read from stdin will be gone
- Now provide a nice help text
- Support ignore filters #24 #40

### CODE REVIEW

**Comment by ye** [comment]
> * Read from stdin will be gone

Did this mean that Unix pipeline usage of `hadolint` will be broken? Oh no!

**Comment by lukasmartinelli** [comment]
> Did this mean that Unix pipeline usage of hadolint will be broken? Oh no!

You can still pipe stuff into hadolint since stdin is also just a file.

```
cat Dockerfile | hadolint /dev/stdin
```

**Comment by ye** [comment]
Good to know that stdin pipes can still be used albeit it's a bit awkward now in the current syntax. A tiny suggestion: can it interpret the dash `-` as the equivalent of `/dev/stdin` like most other unix tools do?

**Comment by lukasmartinelli** [comment]
> Good to know that stdin pipes can still be used albeit it's a bit awkward now in the current syntax. A tiny suggestion: can it interpret the dash - as the equivalent of /dev/stdin like most other unix tools do?
>  👍 1

Good idea. Low hanging fruit. Done in https://github.com/lukasmartinelli/hadolint/commit/e337f71657f23f5cec36e64686becf671eafa3b6

Pattern matching to the rescue.

```haskell
parseFilename :: String -> String
parseFilename "-" = "/dev/stdin"
parseFilename s = s
```

**Pull request merged**
